<?php
$flash=$this->flashMessenger()
    ->setMessageOpenFormat('<div%s>')
    ->setMessageSeparatorString('')
    ->setMessageCloseString('</div>');
?>
<?php
$this->headTitle("aaaa");
$form = $this->form;
$form->setAttribute('action', $this->url("setup/cursus/actions-cursus",array("controller"=>"cursus","action"=>"add-cursus"),array("query"=>array("lng"=>($this->langue=="fr_FR" ? "ar" : 'fr'))),true));

$form->prepare();
$formLabel = $this->plugin('formLabel');
?>
<div class="row">

    <div class="col-md-12" dir="rtl">
        <div class="box">
            <div class="box-header with-border">
                <h3><?=$this->translate("Cursus_title_create",null,'fr_FR')?></h3>

            </div>
            <div class="box-body">
                <?php
                echo $this->form()->openTag($form);
                echo $flash->render('save_enseignants',array('btn', 'btn-danger'));
                ?>
                <div class="row">
                    <div class="col-md-12">
                        <fieldset>
                            <legend><?=$this->translate("Cursus_title_create",null,'fr_FR')?></legend>
                            <div class="form-group">
                                <?php
                                $eltForm = $form->get('id');
                                echo $formLabel->openTag(). $this->translate($eltForm->getOption('label'),null,'fr_FR') ." ";
                                echo $this->formInput($eltForm);
                                echo $this->formElementErrors($eltForm);
                                echo $formLabel->closeTag();
                                ?>
                            </div>

                            <div class="form-group">
                                <?php
                                $eltForm = $form->get('label',null,'fr_FR');
                                echo $formLabel->openTag(). $this->translate($eltForm->getOption('label'),null,'fr_FR') ." ";
                                echo $this->formInput($eltForm);
                                echo $this->formElementErrors($eltForm);
                                echo $formLabel->closeTag();
                                ?>
                            </div>  
                        </fieldset> 
                    </div> 
                </div> 

                <?php
                $eltForm = $form->get('save_Cursusform');
                $eltForm->setValue($this->translate($eltForm->getValue(),null,'fr_FR'));
                
                echo $this->formSubmit($eltForm);
               // echo $this->formElement($form->get('save_Cursusform'));
                
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>



