  <!-- Tell the browser to be responsive to screen width -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    
<?php
  

// Font Awesome -->
$this->headLink() ->prependStylesheet('/template/AdminLTE3/plugins/fontawesome-free/css/all.min.css');
//Tempusdominus Bbootstrap 4
$this->headLink() ->prependStylesheet('/template/AdminLTE3/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css');
//iCheck -->
$this->headLink() ->prependStylesheet('/template/AdminLTE3/plugins/icheck-bootstrap/icheck-bootstrap.min.css');
//JQVMap -->
$this->headLink() ->prependStylesheet('/template/AdminLTE3/plugins/jqvmap/jqvmap.min.css');
//Theme style -->
$this->headLink() ->prependStylesheet('/template/AdminLTE3/dist/css/adminlte.min.css');
//overlayScrollbars -->
$this->headLink() ->prependStylesheet('/template/AdminLTE3/plugins/overlayScrollbars/css/OverlayScrollbars.min.css');
// Daterange picker -->
$this->headLink() ->prependStylesheet('/template/AdminLTE3/plugins/daterangepicker/daterangepicker.css');
// summernote -->
$this->headLink() ->prependStylesheet('/template/AdminLTE3/plugins/summernote/summernote-bs4.css');


?>  
<?php echo $this->headLink(); ?>