 
<!-- jQuery -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/plugins/jquery/jquery.min.js');?>
<!-- jQuery UI 1.11.4 -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/plugins/jquery-ui/jquery-ui.min.js');?>
 
<!-- Bootstrap 4 -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/plugins/bootstrap/js/bootstrap.bundle.min.js');?>
<!-- ChartJS -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/plugins/chart.js/Chart.min.js');?>
<!-- Sparkline -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/plugins/sparklines/sparkline.js');?>
<!-- JQVMap -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/plugins/jqvmap/jquery.vmap.min.js');?>
<?php  $this->headScript()->appendFile('/template/AdminLTE3/plugins/jqvmap/maps/jquery.vmap.usa.js');?>
<!-- jQuery Knob Chart -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/plugins/jquery-knob/jquery.knob.min.js');?>
<!-- daterangepicker -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/plugins/moment/moment.min.js');?>
<?php  $this->headScript()->appendFile('/template/AdminLTE3/plugins/daterangepicker/daterangepicker.js');?>
<!-- Tempusdominus Bootstrap 4 -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js');?>
<!-- Summernote -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/plugins/summernote/summernote-bs4.min.js');?>
<!-- overlayScrollbars -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js');?>
<!-- AdminLTE App -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/dist/js/adminlte.js');?>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/dist/js/pages/dashboard.js');?>
<!-- AdminLTE for demo purposes -->
<?php  $this->headScript()->appendFile('/template/AdminLTE3/dist/js/demo.js');?>
 

<?php echo $this->headScript();?>

<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>



