  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo --> 
    <?=Limostr\Tools\Template::GenView("layout/BrandLogo",  'layouts\adminlte3\map_template.php','layouts/adminlte3')?>
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) --> 
      <?=Limostr\Tools\Template::GenView("layout/SidebarUserPanel",  'layouts\adminlte3\map_template.php','layouts/adminlte3')?>
      <!-- Sidebar Menu -->
      <?=Limostr\Tools\Template::GenView("layout/SidebarMenu",  'layouts\adminlte3\map_template.php','layouts/adminlte3')?>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>