<?php
return [
    'service_manager' => [
        'factories' => [
            \SmartCursus\V1\Rest\Metacontext\MetacontextResource::class => \SmartCursus\V1\Rest\Metacontext\MetacontextResourceFactory::class,
            \SmartCursus\V1\Rest\Elementmetaprocess\ElementmetaprocessResource::class => \SmartCursus\V1\Rest\Elementmetaprocess\ElementmetaprocessResourceFactory::class,
            \SmartCursus\V1\Rest\Elementmetapassruls\ElementmetapassrulsResource::class => \SmartCursus\V1\Rest\Elementmetapassruls\ElementmetapassrulsResourceFactory::class,
            \SmartCursus\V1\Rest\Metamodelsworker\MetamodelsworkerResource::class => \SmartCursus\V1\Rest\Metamodelsworker\MetamodelsworkerResourceFactory::class,
            \SmartCursus\V1\Rest\Linkedprocess\LinkedprocessResource::class => \SmartCursus\V1\Rest\Linkedprocess\LinkedprocessResourceFactory::class,
            \SmartCursus\V1\Rest\LastElement\LastElementResource::class => \SmartCursus\V1\Rest\LastElement\LastElementResourceFactory::class,
            \SmartCursus\V1\Rest\RevokeToken\RevokeTokenResource::class => \SmartCursus\V1\Rest\RevokeToken\RevokeTokenResourceFactory::class,
            \SmartCursus\V1\Rest\User\UserResource::class => \SmartCursus\V1\Rest\User\UserResourceFactory::class,
            \SmartCursus\V1\Rest\UserType\UserTypeResource::class => \SmartCursus\V1\Rest\UserType\UserTypeResourceFactory::class,
            \SmartCursus\V1\Rest\FindProcess\FindProcessResource::class => \SmartCursus\V1\Rest\FindProcess\FindProcessResourceFactory::class,
            \SmartCursus\V1\Rest\Degree\DegreeResource::class => \SmartCursus\V1\Rest\Degree\DegreeResourceFactory::class,
            \SmartCursus\V1\Rest\Session\SessionResource::class => \SmartCursus\V1\Rest\Session\SessionResourceFactory::class,
            \SmartCursus\V1\Rest\Subject\SubjectResource::class => \SmartCursus\V1\Rest\Subject\SubjectResourceFactory::class,
            \SmartCursus\V1\Rest\Unit\UnitResource::class => \SmartCursus\V1\Rest\Unit\UnitResourceFactory::class,
        ],
    ],
    'router' => [
        'routes' => [
            'smart-cursus.rest.metacontext' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/metacontext[/:metacontext_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\Metacontext\\Controller',
                    ],
                ],
            ],
            'smart-cursus.rest.elementmetaprocess' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/elementmetaprocess[/:elementmetaprocess_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\Elementmetaprocess\\Controller',
                    ],
                ],
            ],
            'smart-cursus.rest.elementmetapassruls' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/elementmetapassruls[/:elementmetapassruls_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\Elementmetapassruls\\Controller',
                    ],
                ],
            ],
            'smart-cursus.rest.metamodelsworker' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/metamodelsworker[/:metamodelsworker_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\Metamodelsworker\\Controller',
                    ],
                ],
            ],
            'smart-cursus.rest.linkedprocess' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/linkedprocess[/:linkedprocess_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\Linkedprocess\\Controller',
                    ],
                ],
            ],
            'smart-cursus.rest.last-element' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/last-element[/:last_element_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\LastElement\\Controller',
                    ],
                ],
            ],
            'smart-cursus.rest.revoke-token' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/revoke-token[/:revoke_token_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\RevokeToken\\Controller',
                    ],
                ],
            ],
            'smart-cursus.rest.user' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/user[/:user_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\User\\Controller',
                    ],
                ],
            ],
            'smart-cursus.rest.user-type' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/user-type[/:user_type_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\UserType\\Controller',
                    ],
                ],
            ],
            'smart-cursus.rest.find-process' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/find-process[/:find_process_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\FindProcess\\Controller',
                    ],
                ],
            ],
            'smart-cursus.rest.degree' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/degree[/:degree_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\Degree\\Controller',
                    ],
                ],
            ],
            'smart-cursus.rest.session' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/session[/:session_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\Session\\Controller',
                    ],
                ],
            ],
            'smart-cursus.rest.subject' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/subject[/:subject_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\Subject\\Controller',
                    ],
                ],
            ],
            'smart-cursus.rest.unit' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/unit[/:unit_id]',
                    'defaults' => [
                        'controller' => 'SmartCursus\\V1\\Rest\\Unit\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'api-tools-versioning' => [
        'uri' => [
            0 => 'smart-cursus.rest.metacontext',
            2 => 'smart-cursus.rest.elementmetaprocess',
            3 => 'smart-cursus.rest.elementmetapassruls',
            4 => 'smart-cursus.rest.metamodelsworker',
            5 => 'smart-cursus.rest.linkedprocess',
            7 => 'smart-cursus.rest.last-element',
            9 => 'smart-cursus.rest.revoke-token',
            10 => 'smart-cursus.rest.user',
            11 => 'smart-cursus.rest.user-type',
            12 => 'smart-cursus.rest.find-process',
            13 => 'smart-cursus.rest.degree',
            14 => 'smart-cursus.rest.session',
            15 => 'smart-cursus.rest.subject',
            16 => 'smart-cursus.rest.unit',
        ],
    ],
    'api-tools-rest' => [
        'SmartCursus\\V1\\Rest\\Metacontext\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\Metacontext\MetacontextResource::class,
            'route_name' => 'smart-cursus.rest.metacontext',
            'route_identifier_name' => 'metacontext_id',
            'collection_name' => 'metacontext',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\Metacontext\MetacontextEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\Metacontext\MetacontextCollection::class,
            'service_name' => 'Metacontext',
        ],
        'SmartCursus\\V1\\Rest\\Elementmetaprocess\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\Elementmetaprocess\ElementmetaprocessResource::class,
            'route_name' => 'smart-cursus.rest.elementmetaprocess',
            'route_identifier_name' => 'elementmetaprocess_id',
            'collection_name' => 'elementmetaprocess',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\Elementmetaprocess\ElementmetaprocessEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\Elementmetaprocess\ElementmetaprocessCollection::class,
            'service_name' => 'Elementmetaprocess',
        ],
        'SmartCursus\\V1\\Rest\\Elementmetapassruls\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\Elementmetapassruls\ElementmetapassrulsResource::class,
            'route_name' => 'smart-cursus.rest.elementmetapassruls',
            'route_identifier_name' => 'elementmetapassruls_id',
            'collection_name' => 'elementmetapassruls',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\Elementmetapassruls\ElementmetapassrulsEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\Elementmetapassruls\ElementmetapassrulsCollection::class,
            'service_name' => 'Elementmetapassruls',
        ],
        'SmartCursus\\V1\\Rest\\Metamodelsworker\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\Metamodelsworker\MetamodelsworkerResource::class,
            'route_name' => 'smart-cursus.rest.metamodelsworker',
            'route_identifier_name' => 'metamodelsworker_id',
            'collection_name' => 'metamodelsworker',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\Metamodelsworker\MetamodelsworkerEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\Metamodelsworker\MetamodelsworkerCollection::class,
            'service_name' => 'Metamodelsworker',
        ],
        'SmartCursus\\V1\\Rest\\Linkedprocess\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\Linkedprocess\LinkedprocessResource::class,
            'route_name' => 'smart-cursus.rest.linkedprocess',
            'route_identifier_name' => 'linkedprocess_id',
            'collection_name' => 'linkedprocess',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\Linkedprocess\LinkedprocessEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\Linkedprocess\LinkedprocessCollection::class,
            'service_name' => 'linkedprocess',
        ],
        'SmartCursus\\V1\\Rest\\LastElement\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\LastElement\LastElementResource::class,
            'route_name' => 'smart-cursus.rest.last-element',
            'route_identifier_name' => 'last_element_id',
            'collection_name' => 'last_element',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\LastElement\LastElementEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\LastElement\LastElementCollection::class,
            'service_name' => 'LastElement',
        ],
        'SmartCursus\\V1\\Rest\\RevokeToken\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\RevokeToken\RevokeTokenResource::class,
            'route_name' => 'smart-cursus.rest.revoke-token',
            'route_identifier_name' => 'revoke_token_id',
            'collection_name' => 'revoke_token',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\RevokeToken\RevokeTokenEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\RevokeToken\RevokeTokenCollection::class,
            'service_name' => 'RevokeToken',
        ],
        'SmartCursus\\V1\\Rest\\User\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\User\UserResource::class,
            'route_name' => 'smart-cursus.rest.user',
            'route_identifier_name' => 'user_id',
            'collection_name' => 'user',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\User\UserEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\User\UserCollection::class,
            'service_name' => 'User',
        ],
        'SmartCursus\\V1\\Rest\\UserType\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\UserType\UserTypeResource::class,
            'route_name' => 'smart-cursus.rest.user-type',
            'route_identifier_name' => 'user_type_id',
            'collection_name' => 'user_type',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\UserType\UserTypeEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\UserType\UserTypeCollection::class,
            'service_name' => 'UserType',
        ],
        'SmartCursus\\V1\\Rest\\FindProcess\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\FindProcess\FindProcessResource::class,
            'route_name' => 'smart-cursus.rest.find-process',
            'route_identifier_name' => 'find_process_id',
            'collection_name' => 'find_process',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\FindProcess\FindProcessEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\FindProcess\FindProcessCollection::class,
            'service_name' => 'FindProcess',
        ],
        'SmartCursus\\V1\\Rest\\Degree\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\Degree\DegreeResource::class,
            'route_name' => 'smart-cursus.rest.degree',
            'route_identifier_name' => 'degree_id',
            'collection_name' => 'degree',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\Degree\DegreeEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\Degree\DegreeCollection::class,
            'service_name' => 'Degree',
        ],
        'SmartCursus\\V1\\Rest\\Session\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\Session\SessionResource::class,
            'route_name' => 'smart-cursus.rest.session',
            'route_identifier_name' => 'session_id',
            'collection_name' => 'session',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\Session\SessionEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\Session\SessionCollection::class,
            'service_name' => 'Session',
        ],
        'SmartCursus\\V1\\Rest\\Subject\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\Subject\SubjectResource::class,
            'route_name' => 'smart-cursus.rest.subject',
            'route_identifier_name' => 'subject_id',
            'collection_name' => 'subject',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\Subject\SubjectEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\Subject\SubjectCollection::class,
            'service_name' => 'subject',
        ],
        'SmartCursus\\V1\\Rest\\Unit\\Controller' => [
            'listener' => \SmartCursus\V1\Rest\Unit\UnitResource::class,
            'route_name' => 'smart-cursus.rest.unit',
            'route_identifier_name' => 'unit_id',
            'collection_name' => 'unit',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \SmartCursus\V1\Rest\Unit\UnitEntity::class,
            'collection_class' => \SmartCursus\V1\Rest\Unit\UnitCollection::class,
            'service_name' => 'unit',
        ],
    ],
    'api-tools-content-negotiation' => [
        'controllers' => [
            'SmartCursus\\V1\\Rest\\Metacontext\\Controller' => 'Json',
            'SmartCursus\\V1\\Rest\\Elementmetaprocess\\Controller' => 'HalJson',
            'SmartCursus\\V1\\Rest\\Elementmetapassruls\\Controller' => 'HalJson',
            'SmartCursus\\V1\\Rest\\Metamodelsworker\\Controller' => 'HalJson',
            'SmartCursus\\V1\\Rest\\Linkedprocess\\Controller' => 'HalJson',
            'SmartCursus\\V1\\Rest\\LastElement\\Controller' => 'HalJson',
            'SmartCursus\\V1\\Rest\\RevokeToken\\Controller' => 'HalJson',
            'SmartCursus\\V1\\Rest\\User\\Controller' => 'HalJson',
            'SmartCursus\\V1\\Rest\\UserType\\Controller' => 'HalJson',
            'SmartCursus\\V1\\Rest\\FindProcess\\Controller' => 'HalJson',
            'SmartCursus\\V1\\Rest\\Degree\\Controller' => 'HalJson',
            'SmartCursus\\V1\\Rest\\Session\\Controller' => 'HalJson',
            'SmartCursus\\V1\\Rest\\Subject\\Controller' => 'HalJson',
            'SmartCursus\\V1\\Rest\\Unit\\Controller' => 'HalJson',
        ],
        'accept_whitelist' => [
            'SmartCursus\\V1\\Rest\\Metacontext\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Elementmetaprocess\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Elementmetapassruls\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Metamodelsworker\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Linkedprocess\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\LastElement\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\RevokeToken\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\User\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\UserType\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\FindProcess\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Degree\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Session\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Subject\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Unit\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'SmartCursus\\V1\\Rest\\Metacontext\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Elementmetaprocess\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Elementmetapassruls\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Metamodelsworker\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Linkedprocess\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\LastElement\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\RevokeToken\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\User\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\UserType\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\FindProcess\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Degree\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Session\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Subject\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
            'SmartCursus\\V1\\Rest\\Unit\\Controller' => [
                0 => 'application/vnd.smart-cursus.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'api-tools-hal' => [
        'metadata_map' => [
            \SmartCursus\V1\Rest\Metacontext\MetacontextEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.metacontext',
                'route_identifier_name' => 'metacontext_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\Metacontext\MetacontextCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.metacontext',
                'route_identifier_name' => 'metacontext_id',
                'is_collection' => true,
            ],
            \SmartCursus\V1\Rest\Elementmetaprocess\ElementmetaprocessEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.elementmetaprocess',
                'route_identifier_name' => 'elementmetaprocess_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\Elementmetaprocess\ElementmetaprocessCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.elementmetaprocess',
                'route_identifier_name' => 'elementmetaprocess_id',
                'is_collection' => true,
            ],
            \SmartCursus\V1\Rest\Elementmetapassruls\ElementmetapassrulsEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.elementmetapassruls',
                'route_identifier_name' => 'elementmetapassruls_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\Elementmetapassruls\ElementmetapassrulsCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.elementmetapassruls',
                'route_identifier_name' => 'elementmetapassruls_id',
                'is_collection' => true,
            ],
            \SmartCursus\V1\Rest\Metamodelsworker\MetamodelsworkerEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.metamodelsworker',
                'route_identifier_name' => 'metamodelsworker_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\Metamodelsworker\MetamodelsworkerCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.metamodelsworker',
                'route_identifier_name' => 'metamodelsworker_id',
                'is_collection' => true,
            ],
            \SmartCursus\V1\Rest\Linkedprocess\LinkedprocessEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.linkedprocess',
                'route_identifier_name' => 'linkedprocess_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\Linkedprocess\LinkedprocessCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.linkedprocess',
                'route_identifier_name' => 'linkedprocess_id',
                'is_collection' => true,
            ],
            \SmartCursus\V1\Rest\LastElement\LastElementEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.last-element',
                'route_identifier_name' => 'last_element_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\LastElement\LastElementCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.last-element',
                'route_identifier_name' => 'last_element_id',
                'is_collection' => true,
            ],
            \SmartCursus\V1\Rest\RevokeToken\RevokeTokenEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.revoke-token',
                'route_identifier_name' => 'revoke_token_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\RevokeToken\RevokeTokenCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.revoke-token',
                'route_identifier_name' => 'revoke_token_id',
                'is_collection' => true,
            ],
            \SmartCursus\V1\Rest\User\UserEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.user',
                'route_identifier_name' => 'user_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\User\UserCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.user',
                'route_identifier_name' => 'user_id',
                'is_collection' => true,
            ],
            \SmartCursus\V1\Rest\UserType\UserTypeEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.user-type',
                'route_identifier_name' => 'user_type_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\UserType\UserTypeCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.user-type',
                'route_identifier_name' => 'user_type_id',
                'is_collection' => true,
            ],
            \SmartCursus\V1\Rest\FindProcess\FindProcessEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.find-process',
                'route_identifier_name' => 'find_process_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\FindProcess\FindProcessCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.find-process',
                'route_identifier_name' => 'find_process_id',
                'is_collection' => true,
            ],
            \SmartCursus\V1\Rest\Degree\DegreeEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.degree',
                'route_identifier_name' => 'degree_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\Degree\DegreeCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.degree',
                'route_identifier_name' => 'degree_id',
                'is_collection' => true,
            ],
            \SmartCursus\V1\Rest\Session\SessionEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.session',
                'route_identifier_name' => 'session_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\Session\SessionCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.session',
                'route_identifier_name' => 'session_id',
                'is_collection' => true,
            ],
            \SmartCursus\V1\Rest\Subject\SubjectEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.subject',
                'route_identifier_name' => 'subject_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\Subject\SubjectCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.subject',
                'route_identifier_name' => 'subject_id',
                'is_collection' => true,
            ],
            \SmartCursus\V1\Rest\Unit\UnitEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.unit',
                'route_identifier_name' => 'unit_id',
                'hydrator' => \Laminas\Hydrator\ObjectPropertyHydrator::class,
            ],
            \SmartCursus\V1\Rest\Unit\UnitCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'smart-cursus.rest.unit',
                'route_identifier_name' => 'unit_id',
                'is_collection' => true,
            ],
        ],
    ],
    'api-tools-mvc-auth' => [
        'authorization' => [
            'SmartCursus\\V1\\Rest\\Metacontext\\Controller' => [
                'collection' => [
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
                'entity' => [
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
            ],
            'SmartCursus\\V1\\Rest\\User\\Controller' => [
                'collection' => [
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
                'entity' => [
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ],
            ],
        ],
    ],
    'api-tools' => [
        'db-connected' => [],
    ],
];
