 <!-- Navbar -->
 <nav class="main-header navbar navbar-expand navbar-white navbar-light">
 <?=Limostr\Tools\Template::GenView("layout/LeftNavbar",  'layouts\adminlte3\map_template.php','layouts/adminlte3')?>
 <?=Limostr\Tools\Template::GenView("layout/SearcheForm",  'layouts\adminlte3\map_template.php','layouts/adminlte3')?>
 <?=Limostr\Tools\Template::GenView("layout/RightNavbar",  'layouts\adminlte3\map_template.php','layouts/adminlte3')?>
 
</nav>
<!-- /.navbar -->