<!-- Right navbar links -->
<ul class="navbar-nav ml-auto">
<?=Limostr\Tools\Template::GenView("layout/MessagesMenu",  'layouts\adminlte3\map_template.php','layouts/adminlte3')?>
<?=Limostr\Tools\Template::GenView("layout/NotificationsMenu",  'layouts\adminlte3\map_template.php','layouts/adminlte3')?>


<li class="nav-item">
  <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
    <i class="fas fa-th-large"></i>
  </a>
</li>
</ul>