<li class="nav-item has-treeview menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
             <?=Limostr\Tools\Template::GenView("layout/DashBordLink",  'layouts\adminlte3\map_template.php','layouts/adminlte3')?>

            </ul>
          </li>