<?php

/**
 * Configuration file generated by Laminas API Tools Admin
 *
 * The previous config file has been stored in ./config/modules.config.old
 */
return [
    'Laminas\\I18n',
    'Laminas\\Mvc\\Plugin\\FlashMessenger',
    'Laminas\\Form',
    'Laminas\\Navigation',
    'Laminas\\Mail',
    'Laminas\\Session',
    'Laminas\\Mvc\\Console',
    'Laminas\\Db',
    'Laminas\\Filter',
    'Laminas\\Hydrator',
    'Laminas\\InputFilter',
    'Laminas\\Paginator',
    'Laminas\\Router',
    'Laminas\\Validator',
    'Laminas\\ApiTools',
    'Laminas\\ApiTools\\Documentation',
    'Laminas\\ApiTools\\ApiProblem',
    'Laminas\\ApiTools\\Configuration',
    'Laminas\\ApiTools\\OAuth2',
    'Laminas\\ApiTools\\MvcAuth',
    'Laminas\\ApiTools\\Hal',
    'Laminas\\ApiTools\\ContentNegotiation',
    'Laminas\\ApiTools\\ContentValidation',
    'Laminas\\ApiTools\\Rest',
    'Laminas\\ApiTools\\Rpc',
    'Laminas\\ApiTools\\Versioning',
    'Laminas\\DeveloperTools',
    'ZfrCors',
    'Application',
    30 => 'SetupParameters',
    'SmartCursus',
];
