 <!-- Sidebar Menu -->
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <?=Limostr\Tools\Template::GenView("layout/DashBordTree",  'layouts\adminlte3\map_template.php','layouts/adminlte3')?>

    <?=Limostr\Tools\Template::GenView("layout/SimpleLink",  'layouts\adminlte3\map_template.php','layouts/adminlte3')?>
    
    <?=Limostr\Tools\Template::GenView("layout/ItemTree",  'layouts\adminlte3\map_template.php','layouts/adminlte3')?>

    </ul>
</nav>