<?php
declare(strict_types = 1);
$this->headLink() ->prependStylesheet('/admin/bootstrap/css/bootstrap.min.css'); ?>
    <!-- Font Awesome -->
<?php $this->headLink() ->prependStylesheet('/admin/internet/maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'); ?>
    <!-- Ionicons -->
<?php $this->headLink() ->prependStylesheet('/admin/internet/code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css'); ?>
    <!-- Theme style -->
<?php $this->headLink() ->prependStylesheet('/admin/dist/css/AdminLTE.min.css'); ?>
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
<?php $this->headLink() ->prependStylesheet('/admin/dist/css/skins/_all-skins.min.css'); ?>
    <!-- iCheck -->
<?php $this->headLink() ->prependStylesheet('/admin/plugins/iCheck/flat/blue.css'); ?>
    <!-- Morris chart -->
<?php $this->headLink() ->prependStylesheet('/admin/plugins/morris/morris.css'); ?>
    <!-- jvectormap -->
<?php $this->headLink() ->prependStylesheet('/admin/plugins/jvectormap/jquery-jvectormap-1.2.2.css'); ?>
    <!-- Date Picker -->
<?php $this->headLink() ->prependStylesheet('/admin/plugins/datepicker/datepicker3.css'); ?>
    <!-- Daterange picker -->
<?php $this->headLink() ->prependStylesheet('/admin/plugins/daterangepicker/daterangepicker-bs3.css'); ?>
    <!-- bootstrap wysihtml5 - text editor -->
<?php $this->headLink() ->prependStylesheet('/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'); ?>

    <!-- icheck 1.0.1 -->
<?php $this->headLink() ->prependStylesheet('/admin/plugins/iCheck/all.css'); ?>

    <!-- Layout Split http://layout.jquery-dev.com/-->
<?php  $this->headLink() ->prependStylesheet('/admin/plugins/jslayout/layout-default-latestold.css'); ?>

    <!----Validator ---->
<?php $this->headLink() ->appendStylesheet('/ressources/js/validator/css/validationEngine.jquery.css'); ?>



<?php $this->headLink() ->appendStylesheet('/ressources/js/quickselect/bootstrap-chosen.css'); ?>

<?php  $this->headLink() ->appendStylesheet('/ressources/js/simplemodale/css/confirm.css');?>

<?php  $this->headLink() ->appendStylesheet('/ressources/js/treeview2/src/skin-lion/ui.fancytree.css');?>

<?php $this->headLink() ->appendStylesheet('/admin/plugins/datatables/css/dataTables.bootstrap.min.css');?>
<?php $this->headLink() ->prependStylesheet('/ressources/application/visiontrijs/svjlib/jquery.svg.css'); ?>


<?php $this->headLink() ->prependStylesheet('/ressources/msdropdown/dd.css'); ?>

<?php $this->headLink() ->appendStylesheet('/admin/plugins/tabs/tabs.css');?>

<?php $this->headLink() ->appendStylesheet('/admin/plugins/tabs/tabs.sideways.css');?>
<?php $this->headLink() ->appendStylesheet('/admin/plugins/tabs/bootstrap.vertical-tabs.min.css');?>

<?php $this->headLink() ->prependStylesheet('/css/menu.css'); ?>


<?php echo $this->headLink(); ?>