<?php
declare(strict_types = 1);
/**
 * Created by PhpStorm.
 * User: username
 * Date: 05/01/2016
 * Time: 15:06
 */?>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<?php  $this->headScript()->appendFile('/admin/internet/oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js');?>
<?php  $this->headScript()->appendFile('/admin/internet/oss.maxcdn.com/respond/1.4.2/respond.min.js');?>
<![endif]-->

<!-- jQuery UI 1.11.4 -->
<?php  $this->headScript()->prependFile('/admin/internet/code.jquery.com/ui/1.11.4/jquery-ui.min.js');?>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<!-- jQuery 2.1.4 -->
<?php  $this->headScript()->prependFile('/admin/plugins/jQuery/jQuery-2.1.4.min.js');?>

<!-- Bootstrap 3.3.5 -->
<?php  $this->headScript()->appendFile('/admin/bootstrap/js/bootstrap.min.js');?>
<!-- Morris.js charts -->
<?php  $this->headScript()->appendFile('/admin/internet/cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js');?>
<?php  $this->headScript()->appendFile('/admin/plugins/morris/morris.min.js');?>
<!-- Sparkline -->
<?php  $this->headScript()->appendFile('/admin/plugins/sparkline/jquery.sparkline.min.js');?>
<!-- jvectormap -->
<?php  $this->headScript()->appendFile('/admin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js');?>
<?php  $this->headScript()->appendFile('/admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js');?>
<!-- jQuery Knob Chart -->
<?php  $this->headScript()->appendFile('/admin/plugins/knob/jquery.knob.js');?>
<!-- daterangepicker -->
<?php  $this->headScript()->appendFile('/admin/internet/cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js');?>
<?php  $this->headScript()->appendFile('/admin/plugins/daterangepicker/daterangepicker.js');?>
<!-- datepicker -->
<?php  $this->headScript()->appendFile('/admin/plugins/datepicker/bootstrap-datepicker.js');?>
<!-- Bootstrap WYSIHTML5 -->
<?php  $this->headScript()->appendFile('/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js');?>
<!-- Slimscroll -->
<?php  $this->headScript()->appendFile('/admin/plugins/slimScroll/jquery.slimscroll.min.js');?>
<!-- FastClick -->
<?php  $this->headScript()->appendFile('/admin/plugins/fastclick/fastclick.js');?>
<!-- AdminLTE App -->
<?php  $this->headScript()->appendFile('/admin/dist/js/app.min.js');?>

<?php  $this->headScript()->appendFile('/ressources/js/quickselect/chosen.jquery.js','text/javascript');?>

<!-- Layout Split http://layout.jquery-dev.com/-->
<?php  $this->headScript()->appendFile('/admin/plugins/jslayout/jquery.layout-latestold.js');?>

<!----Validator---->
<?php  $this->headScript()->appendFile('/ressources/js/validator/jquery.validationEngine.js','text/javascript');?>
<?php  $this->headScript()->appendFile('/ressources/js/jquery.form.js','text/javascript');?>



<?php  $this->headScript()->appendFile('/ressources/js/treeview2/src/jquery.fancytree.js','text/javascript');?>

<?php  $this->headScript()->appendFile('/ressources/js/simplemodale/js/confirm.js','text/javascript');?>

<?php  $this->headScript()->appendFile('/ressources/js/jquery.form.js','text/javascript');?>
<?php  $this->headScript()->appendFile('/ressources/js/validator/languages/jquery.validationEngine-fr.js','text/javascript');?>
<?php  $this->headScript()->appendFile('/ressources/js/validator/jquery.validationEngine.js','text/javascript');?>
<!-- icheck 1.0.1 -->
<?php  $this->headScript()->appendFile('/admin/plugins/iCheck/icheck.min.js');?>

<?php  $this->headScript()->appendFile('/admin/bootstrap/js/bootbox.min.js');?>


<?php  $this->headScript()->appendFile('/ressources/application/visiontrijs/svjlib/jquery.svg.js');?>



<?php  $this->headScript()->appendFile('/ressources/msdropdown/jquery.dd.min.js');?>

<?php  $this->headScript()->appendFile('/admin/plugins/fastclick/fastclick.js');?>

<?php  $this->headScript()->appendFile('/admin/plugins/chartjs/Chart.min.js');?>


<?php echo $this->headScript();?>

<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>



