<!-- Control Sidebar -->
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-settings-scool" data-toggle="tab" ><i class="fa fa-graduation-cap"></i></a></li>
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane active" id="control-sidebar-settings-scool">
            <h3 class="control-sidebar-heading">Vos choix d'activité</h3>

            <ul class="control-sidebar-menu">
                <li>
                    <a href="#">
                        <i class="menu-icon fa fa-user-secret bg-red"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Administration <input type="checkbox"  class="form-group flat-red"></h4>
                            <p>Gestion des formations</p>
                        </div>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <i class="menu-icon fa fa-users bg-light-blue"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Operationnel <input type="checkbox"  class="form-group flat-blue"></h4>
                            <p>Gestion des scolarité</p>
                        </div>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <i class="menu-icon fa fa-user-md bg-yellow"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Coordinateur <input type="checkbox"  class="flat-yellow"></h4>
                            <p>Gestion pour les Coordinateurs</p>
                        </div>
                    </a>
                </li>
            </ul>

            <form method="post">
                <h5 class="control-sidebar-heading">Activité</h5>
                <div class="form-group">

                    <label class="control-sidebar-subheading" >
                        Année universitaire
                        <div style="color:#000000;">
                        <select id="mainanneescolaire" name= "mainanneescolaire" class="pull-right form-control">
                            <option value="">Selectionner une formation</option>

                        </select>
                        </div>
                    </label>
                    <p>Années universitaires</p>
                    <label class="control-sidebar-subheading">
                        Diplôme active
                        <div style="color:#000000;">
                            <select id="diplomeactive" name= "diplomeactive" class="pull-right form-control">

                            </select>
                        </div>
                    </label>
                    <p>Dipôme active</p>
                    <label class="control-sidebar-subheading">
                        <span>Formation</span>
                        <div style="color:#000000;">
                            <select id="formationactive" name= "formationactive" class="pull-right form-control">

                            </select>
                        </div>
                    </label>
                    <p>
                        Formations ayons une session de préinscription active
                    </p>
                    <p align="center">
                       <a class="btn btn-app" onclick="todashboard();" href="#">
                            <i class="fa fa-refresh"></i> Actualiser
                        </a>
                    </p>

                    <p>
                        Ces informations sont obligatoire
                    </p>
                </div>
            </form>

        </div>
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="#">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="#">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-warning pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right">
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="#" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>

<!-- /.control-sidebar -->