<?php
declare(strict_types = 1);
//$_user=Zend_Auth::getInstance()->getIdentity();
?>

<div class="user-panel">
    <div class="pull-left image">
        <img src="/admin/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
    </div>
    <div class="pull-left info">
        <p><?php //$_user->user['nom']?> <?php //$_user->user['prenom']?></p>
        <a href="#"><i class="fa fa-circle text-success"></i>  Online </a>
    </div>
</div>